//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.Fresher.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.Fresher.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉ cảnh báo.
        /// </summary>
        internal static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string checkDuplicate {
            get {
                return ResourceManager.GetString("checkDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dư có.
        /// </summary>
        internal static string Credit {
            get {
                return ResourceManager.GetString("Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách hàng.
        /// </summary>
        internal static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  không được lớn hơn ngày hiện tại!.
        /// </summary>
        internal static string DateMessage {
            get {
                return ResourceManager.GetString("DateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dư nợ.
        /// </summary>
        internal static string Debt {
            get {
                return ResourceManager.GetString("Debt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa không thành công. Không thể xóa danh mục cha nếu chưa xóa danh mục con..
        /// </summary>
        internal static string Delete_Not_Success {
            get {
                return ResourceManager.GetString("Delete_Not_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  đã bị trùng.
        /// </summary>
        internal static string DuplicateCode {
            get {
                return ResourceManager.GetString("DuplicateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên.
        /// </summary>
        internal static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nữ.
        /// </summary>
        internal static string Enum_Gender_Female {
            get {
                return ResourceManager.GetString("Enum_Gender_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nam.
        /// </summary>
        internal static string Enum_Gender_Male {
            get {
                return ResourceManager.GetString("Enum_Gender_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khác.
        /// </summary>
        internal static string Enum_Gender_Other {
            get {
                return ResourceManager.GetString("Enum_Gender_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anh.
        /// </summary>
        internal static string Enum_Prefix_Brother {
            get {
                return ResourceManager.GetString("Enum_Prefix_Brother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ông.
        /// </summary>
        internal static string Enum_Prefix_Grandfather {
            get {
                return ResourceManager.GetString("Enum_Prefix_Grandfather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bà.
        /// </summary>
        internal static string Enum_Prefix_Grandma {
            get {
                return ResourceManager.GetString("Enum_Prefix_Grandma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mr.
        /// </summary>
        internal static string Enum_Prefix_Mr {
            get {
                return ResourceManager.GetString("Enum_Prefix_Mr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mrs.
        /// </summary>
        internal static string Enum_Prefix_Mrs {
            get {
                return ResourceManager.GetString("Enum_Prefix_Mrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ms.
        /// </summary>
        internal static string Enum_Prefix_Ms {
            get {
                return ResourceManager.GetString("Enum_Prefix_Ms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chị.
        /// </summary>
        internal static string Enum_Prefix_Sister {
            get {
                return ResourceManager.GetString("Enum_Prefix_Sister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chú.
        /// </summary>
        internal static string Enum_Prefix_Uncle {
            get {
                return ResourceManager.GetString("Enum_Prefix_Uncle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn.
        /// </summary>
        internal static string Enum_Prefix_You {
            get {
                return ResourceManager.GetString("Enum_Prefix_You", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra vui lòng liên hệ MISA.
        /// </summary>
        internal static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  không đúng định dạng!.
        /// </summary>
        internal static string FormatCode {
            get {
                return ResourceManager.GetString("FormatCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưỡng tính.
        /// </summary>
        internal static string Hermaphrodite {
            get {
                return ResourceManager.GetString("Hermaphrodite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh Sách Nhân viên.
        /// </summary>
        internal static string ListEmployee {
            get {
                return ResourceManager.GetString("ListEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có số dư.
        /// </summary>
        internal static string NoBalance {
            get {
                return ResourceManager.GetString("NoBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có dữ liệu trả về.
        /// </summary>
        internal static string Null {
            get {
                return ResourceManager.GetString("Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có id.
        /// </summary>
        internal static string NullId {
            get {
                return ResourceManager.GetString("NullId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  không được phép trống!.
        /// </summary>
        internal static string NullValue {
            get {
                return ResourceManager.GetString("NullValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bắt buộc nhập.
        /// </summary>
        internal static string Obligate {
            get {
                return ResourceManager.GetString("Obligate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parametter không được bé hơn hoặc bằng 0.
        /// </summary>
        internal static string ParameterFilter {
            get {
                return ResourceManager.GetString("ParameterFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhà cung cấp.
        /// </summary>
        internal static string Supplier {
            get {
                return ResourceManager.GetString("Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã ID không đúng định dạng.
        /// </summary>
        internal static string ValidateId {
            get {
                return ResourceManager.GetString("ValidateId", resourceCulture);
            }
        }
    }
}
